# a cluster with 3 control-plane nodes and 3 workers with ephemeral container enabled
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: kindregistry
kindV1Alpha4Cluster:
  name: one
  nodes:
    - role: control-plane
    - role: worker
    - role: worker
  featureGates:
    EphemeralContainers: true
  networking:
    apiServerPort: 6443
