version: '3'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4443:443"
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=${APIKEY- }
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - KUBE_ENDPOINT=${KUBE_ENDPOINT- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-./ls/tmp}:/tmp/localstack"
      - "${DATADIR:-./ls/data}:/tmp/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./kubeconfig:/root/.kube/config"

networks:
  default:
    external:
      name: kind
